### ISSUE TITLE
Program a placeholder UI 

### ISSUE THREAD

**Issue by Christer-Bjoerk** [Junior-Game-Dev-Team/Delay-Inevitable#14]
The UI should look like Carl Bisenius's UI/UX wireframe.
[https://www.figma.com/file/wekyY5wOveECGFMsM3woQO/The-Wayward-Horror-Game-UI?type=whiteboard&node-id=0-1](url)

### Acceptance Criteria: 

- Support the new input system
- Player can interact with the UI without getting stuck

**Comment by chadjamesforry** [comment]
Awesome :)
